GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJCdWRpIiwiZW1haWwiOiJidWRpZGlAZ21haWwuY29tIiwiaWF0IjoxNjczMTQ2NzE5LCJleHAiOjE2NzMxNDY3Mzl9.Ops_3DMOLBTloDNp58iv60gGcmOX3D9dGmeIIRGpXis
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Budi",
    "email":"budidi@gmail.com",
    "password":"123425",
    "confPassword":"123425"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"budidi@gmail.com",
    "password":"123425"
}
